---

os: linux
dist: bionic
language: python
services: docker

env:
  global:
    - ROLE_NAME: openwisp2
  jobs:
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu2004
    - MOLECULE_DISTRO: debian10

jobs:
  fast_finish: true

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

script:
  # Run tests.
  - molecule test
  - pip install "openwisp-utils[qa]~=0.5"
  - openwisp-qa-check --skip-isort --skip-flake8 --skip-checkmigrations --skip-black

notifications:
  webhooks:
    - urls:
        # will post a summary as comment on github in case of failure
        - https://www.travisbuddy.com/
      on_success: never
    - urls:
        - https://galaxy.ansible.com/api/v1/notifications/
