---

os: linux
dist: xenial
language: python
services: docker

env:
  global:
    - ROLE_NAME: openwisp2
  jobs:
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian10

jobs:
  fast_finish: true

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-$ROLE_NAME openwisp.$ROLE_NAME
  - cd openwisp.$ROLE_NAME

script:
  # Run tests.
  - molecule test
  - pip install "openwisp-utils[qa]>=0.4.0"
  - openwisp-utils-qa-checks --skip-isort --skip-flake8 --skip-checkmigrations

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
