---

services: docker

if: (type = pull_request) OR (branch = master)

env:
  matrix:
  - distro: 'ubuntu:18.04'
    playbook: test.yml
  - distro: debian:9
    playbook: test.yml
  - distro: debian:10
    playbook: test.yml
  - distro: 'ubuntu:18.04'
    playbook: test_networktopology.yml
  # we don't have the resources now to maintain these distros
  # - distro: fedora:27
  #   playbook: test.yml
  # - distro: fedora:28
  #   playbook: test.yml
  # - distro: centos:7
  #   playbook: test.yml

matrix:
  include:
    - dist: trusty
      env:
        - distro: 'ubuntu:16.04'
          playbook: test.yml

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  # run ansible-lint
  - pip install --user ansible
  - ansible-galaxy install -r tests/requirements.yml
  - pip install --user ansible-lint
  - ln -s $TRAVIS_BUILD_DIR ~/.ansible/roles/role_under_test
  - git clone https://github.com/ansible/galaxy-lint-rules.git
  - mv galaxy-lint-rules ~/galaxy
  - ansible-lint tests/test.yml
  - ansible-lint tests/test_networktopology.yml
  # run ci tests
  - ${PWD}/tests/runtests.sh
  - pip install --user "openwisp-utils[qa]>=0.3.1"
  - openwisp-utils-qa-checks --skip-isort --skip-flake8 --skip-checkmigrations

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
