- name: Update APT package cache
  apt: update_cache=yes
  changed_when: false
  retries: 5
  delay: 10
  register: result
  until: result is success

- name: Install system packages
  apt:
    name:
      - sudo
      - software-properties-common
      - build-essential
      - supervisor
      - nginx
      - openssl
      - libssl-dev
      - libffi-dev
      - python3
      - virtualenv
      - cron
  ignore_errors: yes
  retries: 5
  delay: 10
  register: result
  until: result is success

- name: Install redis 5 if available
  apt:
    name: "redis-server=5:5*"
  notify:
    - reload systemd
    - start redis
  ignore_errors: yes
  register: use_redis5

- name: Install redis 4 (fallback)
  when: use_redis5.failed
  apt:
    name: "redis-server=5:4*"
  notify:
    - reload systemd
    - start redis
  ignore_errors: yes

# On the newer versions of redis, by default redis
# binds to localhost on ipv6 address which wouldn't
# let the service start if the server doesn't have
# ipv6 enabled. Hence, we set redis to listen on ipv4
- name: set redis to listen on ipv4
  notify: start redis
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind 127\.0\.0\.1 ::1'
    line: 'bind 127.0.0.1'
    backrefs: yes

- name: Install spatialite
  when: openwisp2_database.engine == "django.contrib.gis.db.backends.spatialite"
  apt:
    name:
      - sqlite3
      - gdal-bin
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev
      - openssh-client
  retries: 5
  delay: 10
  register: result
  until: result is success
  notify: reload systemd

- name: Install mod-spatialite (may fail on older linux distros)
  when: openwisp2_database.engine == "django.contrib.gis.db.backends.spatialite"
  apt: name=libsqlite3-mod-spatialite
  ignore_errors: yes
  retries: 5
  delay: 10
  register: result
  until: result is success

# fixes issue described in https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user
- name: Install acl if acting as non-root user
  apt: name=acl
  when: ansible_user is not defined or ansible_user != 'root'
  retries: 5
  delay: 10
  register: result
  until: result is success
  ignore_errors: yes

- name: ensure supervisor is started
  service: name=supervisor state=started

- name: Install python2 packages
  when: openwisp2_python in ["python2.7", "python2"]
  apt:
    name:
      - python-pip
      - python-dev
      - python-virtualenv
  retries: 5
  delay: 10
  register: result
  until: result is success

- name: Install python3 packages
  apt:
    name:
      - python3-pip
      - python3-dev
      - python3-virtualenv
  retries: 5
  delay: 10
  register: result
  until: result is success

- name: Install ntp
  when: openwisp2_install_ntp
  apt: name=ntp
  retries: 5
  delay: 10
  register: result
  until: result is success
