- name: Set spatialite_path (Ubuntu >= 18.04 or Debian >= 10)
  set_fact:
    openwisp2_spatialite_path: "mod_spatialite.so"
  when: >
    (ansible_distribution == 'Ubuntu'
    and ansible_distribution_version is version_compare('18.04', 'ge'))
    or (ansible_distribution == 'Debian' and
    ansible_distribution_version is version_compare('10', 'ge'))
