---

- name: Install epel-release (if RedHat/Centos)
  when: ansible_distribution in ['RedHat', 'CentOS']
  yum: name=epel-release state=latest
  notify: reload systemd

- name: Install system packages
  package: name={{ item }} state=latest
  notify: reload systemd
  with_items:
    - sudo
    - gcc
    - supervisor
    - nginx
    - openssl
    - openssl-devel
    - libffi-devel
    - python-devel
    - redis
    - libsemanage-python
    - policycoreutils-python
    - redhat-rpm-config

- name: Install firewall packages
  package: name={{ item }} state=present
  notify: reload systemd
  with_items:
    - python-firewall
    - firewalld
  when: ansible_distribution_major_version|int >= 7

- name: Install spatialite
  when: openwisp2_database.engine == "django.contrib.gis.db.backends.spatialite"
  package: name={{ item }} state=latest
  notify: reload systemd
  with_items:
    - sqlite
    - gdal
    - proj-devel
    - geos-devel
    - libspatialite-devel

# mod-spatialite doesn't seem available on RedHat yet
- name: Set openwisp2_spatialite_path
  set_fact:
    openwisp2_spatialite_path: false

- name: ensure supervisor is started
  service: name=supervisord state=started enabled=yes

- name: ensure nginx is enabled
  service: name=nginx enabled=yes

- name: Install python2 packages
  when: openwisp2_python in ["python2.7", "python2"]
  package: name={{ item }} state=latest
  with_items:
    - python-pip
    - python-virtualenv

- name: Install python3 packages
  when: openwisp2_python == "python3"
  package: name={{ item }} state=latest
  with_items:
    - "{{ python3_package_prefix }}"
    - "{{ python3_package_prefix }}-pip"
    - "{{ python3_package_prefix }}-devel"

- name: Install python wheel (optional, allowed to fail)
  ignore_errors: yes
  package: name={{ item }} state=latest
  with_items:
    - python-wheel
    - "{{ python3_package_prefix }}-wheel"

- name: Install python3 virtualenv
  when: openwisp2_python == "python3" and ansible_distribution == 'Fedora'
  package:
    name: "{{ python3_package_prefix }}-virtualenv"
    state: latest

- name: (CentOS/RedHat) Always install pip
  when: ansible_distribution in ['RedHat', 'CentOS']
  package:
    name: python-pip
    state: latest

- name: (CentOS/RedHat/Fedora) Install/upgrade virtualenv via pip
  pip:
    name: virtualenv
    state: latest

- name: Install ntp
  when: openwisp2_install_ntp
  package:
    name: ntp
    state: latest
